[workspace]
members = [
    "liquidity_pool",
    "liquidity_pool/meta",
    "lending_pool",
    "lending_pool/meta",
    "safety_module",
    "safety_module/meta",
    "common/structs",
    "common/checks",
    "common/tokens",
    "aggregator_mock",
    "aggregator_mock/meta"
]
