[package]
name = "safety-module"
version = "0.0.0"
authors = [" Dharitri <contact@dharitri.org>"]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"
[dependencies.multiversx-sc]
version = "0.41.0"

[dependencies.common-structs]
path = "../common/structs"
[dev-dependencies.multiversx-sc-scenario]
version = "0.41.0"
